version: '3.1'
services:
  rp_db:
    image: mariadb
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "ninja55"
      MYSQL_DATABASE: "rp"
      MYSQL_USER: "dockeruser"
      MYSQL_PASSWORD: "dockerpass"
    ports:
      - 23060:3306
volumes:
    db_data: