spring:
  datasource:
    url: jdbc:mysql://localhost/rp?useSSL=false
    username: dockeruser
    password: dockerpass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8089